// Runs the whole test suite and writes docs/TEST_REPORT.md: environment, results, line coverage and
// a traceability table from each requirement point (docs/requirements.json) to the tests that exercise it.
import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
const root = path.resolve(new URL('..', import.meta.url).pathname);
const outDir = path.join(root, 'test-output'); fs.mkdirSync(outDir, { recursive: true });
const files = fs.readdirSync(path.join(root, 'test')).filter(f => f.endsWith('.test.js')).sort().map(f => 'test/' + f);
const t0 = Date.now();
const run = spawnSync(process.execPath, ['--no-warnings', '--test', '--test-concurrency=1', '--experimental-test-coverage',
  '--test-coverage-include=src/**', '--test-reporter=junit', `--test-reporter-destination=${outDir}/junit.xml`,
  '--test-reporter=lcov', `--test-reporter-destination=${outDir}/lcov.info`, '--test-reporter=spec', '--test-reporter-destination=stdout', ...files],
  { cwd: root, encoding: 'utf8', maxBuffer: 64 << 20 });
fs.writeFileSync(path.join(outDir, 'spec.txt'), run.stdout + run.stderr);
const secs = ((Date.now() - t0) / 1000).toFixed(1);
const xml = fs.readFileSync(path.join(outDir, 'junit.xml'), 'utf8');
const unx = s => s.replace(/&quot;/g, '"').replace(/&apos;/g, "'").replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&amp;/g, '&');
const srcOf = Object.fromEntries(files.map(f => [f, fs.readFileSync(path.join(root, f), 'utf8')]));
const fileOf = name => (Object.entries(srcOf).find(([, src]) => src.includes(name.slice(0, 60).replace(/"/g, '"'))) || ['?'])[0].replace('test/', '');
const cases = [...xml.matchAll(/<testcase name="([^"]*)" time="([\d.]+)" classname="[^"]*"(\/>|>([\s\S]*?)<\/testcase>)/g)]
  .map(m => { const name = unx(unx(m[1])); return { name, secs: Number(m[2]), file: fileOf(name), failed: /<failure/.test(m[4] || ''), skipped: /<skipped/.test(m[4] || '') }; });
const pass = cases.filter(c => !c.failed && !c.skipped).length, failed = cases.filter(c => c.failed);
// coverage from lcov
const lcov = fs.readFileSync(path.join(outDir, 'lcov.info'), 'utf8');
const cov = []; let cur = null;
for (const line of lcov.split('\n')) {
  if (line.startsWith('SF:')) cur = { file: path.relative(root, line.slice(3)), lf: 0, lh: 0, brf: 0, brh: 0, fnf: 0, fnh: 0 };
  else if (/^(LF|LH|BRF|BRH|FNF|FNH):/.test(line)) { const [k, v] = line.split(':'); cur[k.toLowerCase()] = Number(v); }
  else if (line === 'end_of_record' && cur) { cov.push(cur); cur = null; }
}
const tot = k => cov.reduce((a, c) => a + c[k], 0);
const pct = (h, f) => (f ? (100 * h / f).toFixed(1) : '100.0');
// traceability
const reqs = JSON.parse(fs.readFileSync(path.join(root, 'docs/requirements.json'), 'utf8'));
const byReq = {};
for (const c of cases) for (const id of c.name.match(/(BIS|COS)-\d+/g) || []) (byReq[norm(id)] ||= []).push(c);
function norm(id) { const [d, n] = id.split('-'); return `${d}-${String(Number(n)).padStart(2, '0')}`; }
const traced = reqs.filter(r => byReq[r.id]);
const summary = { date: new Date().toISOString(), node: process.version, os: `${os.type()} ${os.release()}`, openssl: spawnSync('openssl', ['version'], { encoding: 'utf8' }).stdout.trim(), tests: cases.length, pass, fail: failed.length, seconds: Number(secs),
  coverage: { lines: pct(tot('lh'), tot('lf')), branches: pct(tot('brh'), tot('brf')), functions: pct(tot('fnh'), tot('fnf')) }, requirementsWithTests: traced.length, requirements: reqs.length };
fs.writeFileSync(path.join(outDir, 'summary.json'), JSON.stringify({ ...summary, cases, byReq: Object.fromEntries(Object.entries(byReq).map(([k, v]) => [k, v.map(c => c.name)])) }, null, 2));
const md = [
  '# Test report', '',
  `Automated test run of the City OS data exchange reference implementation. Generated by \`npm run test:report\` on ${summary.date}.`, '',
  'All tests start a fresh demo city (new certificate authority, database and synthetic data) and talk to it over real HTTPS with mutual TLS, the same way an outside client would. No test uses live city data. Passing these tests shows the software behaves as described; it is not a security audit, a load test or an official approval.', '',
  '## Result', '',
  `| Tests | Passed | Failed | Time |`, `|---|---|---|---|`, `| ${cases.length} | ${pass} | ${failed.length} | ${secs} s |`, '',
  `Environment: Node.js ${summary.node}, ${summary.openssl}, ${summary.os}.`, '',
  '## Code coverage (src/)', '',
  `Lines ${summary.coverage.lines}%, branches ${summary.coverage.branches}%, functions ${summary.coverage.functions}%.`, '',
  '| File | Lines | Branches | Functions |', '|---|---|---|---|',
  ...cov.map(c => `| ${c.file} | ${pct(c.lh, c.lf)}% | ${pct(c.brh, c.brf)}% | ${pct(c.fnh, c.fnf)}% |`), '',
  '## Tests', '',
  '| File | Test | Result | Seconds |', '|---|---|---|---|',
  ...cases.map(c => `| ${c.file} | ${c.name.replace(/\|/g, '\\|')} | ${c.failed ? 'FAIL' : c.skipped ? 'skipped' : 'pass'} | ${c.secs.toFixed(2)} |`), '',
  '## Requirement traceability', '',
  `${traced.length} of ${reqs.length} requirement points are exercised by at least one automated test. Points without a test are either explanatory, out of scope, or checked by reading the documents in docs/ (see the verification PDF for the status of every point).`, '',
  '| Point | Clause | Tests |', '|---|---|---|',
  ...reqs.map(r => `| ${r.id} | ${r.ref.replace(/\|/g, '/')} | ${byReq[r.id] ? byReq[r.id].length + ': ' + byReq[r.id].map(c => c.name.replace(/^(\[[A-Z]+-\d+\])+\s*/, '')).join('; ').replace(/\|/g, '/') : '—'} |`), '',
  ...(failed.length ? ['## Failures', '', ...failed.map(f => `- ${f.file}: ${f.name}`), ''] : []),
];
fs.writeFileSync(path.join(root, 'docs/TEST_REPORT.md'), md.join('\n'));
console.log(`${pass}/${cases.length} passed, lines ${summary.coverage.lines}% covered, ${traced.length}/${reqs.length} requirement points traced. Report: docs/TEST_REPORT.md`);
process.exit(failed.length || run.status ? 1 : 0);
